---

worker_image: mirmika/worker:latest
container_name: worker_service_container
redis_host: redis-instance
postgres_host: database-instance
postgres_db: votes
postgres_user: postgres
worker_host: backend-instance
worker_command: "/bin/bash -c 'dotnet build && dotnet run'"