- name: Kill process using port 5000 (if it exists)
  ansible.builtin.shell: |
    pid=$(lsof -ti:5000)
    if [ -n "$pid" ]; then
      kill -9 $pid
    fi
  ignore_errors: true

- name: Start Vote App Container
  community.docker.docker_container:
    name: vote_app
    image: mirmika/vote:latest  # Replace with your actual image
    state: started
    restart_policy: always
    ports:
      - "5000:5000"
    env:
      FLASK_APP: app.py  
      FLASK_ENV: production  
      REDIS_HOST: "10.0.42.133"  # Ensure the vote app connects to Redis
      DB_HOST: "10.0.42.209"

