# ---
# - name: Pull Docker image and deploy vote
#   hosts: frontend_vote
#   become: yes
#   tasks:
- name: Update apt cache
  hosts: frontend_vote
  ansible.builtin.apt:
    update_cache: yes
- name: Pull the Python Docker image
  package:
    name: docker.io
    state: present
    # name: python:3.9
    # source: pull

- name: Create and start the Docker container
  docker_container:
    name: vote_app_container
    image: python:3.9
    state: started
    restart_policy: always  # This ensures the container restarts on failure
    ports:
      - "5000:5000"
    volumes:
      - /ubuntu/home/vote:/app
    command: >
      /bin/bash -c "
      cd /app &&
      pip install -r requirements.txt &&
      python app.py"
    environment:
      FLASK_APP: app.py  # Optional: Set environment variables for the app
      FLASK_ENV: production

- name: Wait for the application to start
  ansible.builtin.wait_for:
    host: "{{ ansible_host }}"
    port: 5000
    delay: 10
    timeout: 60
  when: server_process.rc == 0

- name: Display success message
  debug:
    msg: "The Vote App is now running on http://localhost:5000"
