---
- name: Pull the Docker image
  community.docker.docker_image:
    name: mirmika/vote
    source: pull
- name: Ensure the /home/ubuntu/vote directory exists
  file:
   path: /home/ubuntu/vote
   state: directory
   owner: ubuntu
   group: ubuntu
   mode: '0755'
- name: Create and start the Docker container
  docker_container:
    name: vote_app_container
    image: mirmika/vote
    state: started
    restart_policy: always  # This ensures the container restarts on failure
    ports:
      - "5000:5000"
    volumes:
      - /home/ubuntu/vote:/app  # Corrected volume path (adjust the path as needed)
    command: >
      /bin/bash -c "
      ls -l /app &&  # Debug the volume content
      cd /app && 
      pip install -r requirements.txt && 
      python app.py"
    env:
      FLASK_APP: app.py  # Optional: Set environment variables for the app
      FLASK_ENV: production

- name: Wait for the application to start
  ansible.builtin.wait_for:
    host: "{{ ansible_host }}"
    port: 5000
    delay: 10
    timeout: 60

- name: Display success message
  debug:
    msg: "The Vote App is now running on http://localhost:5000"
