- name: Start Worker (backend-instance)
  community.docker.docker_container:
    name: worker
    image: mirmika/worker:latest
    state: started
    restart_policy: always
    env:
      REDIS_HOST: "10.0.42.133"
      DB_HOST: "10.0.42.209"

    depends_on:
      - redis  # Ensure Redis starts before the worker
      - db  # Ensure Database starts before the worker
