---
#- name: Load database secrets
  #include_vars:
  #  file: "../../database/vars/secrets.yml"
- name: Pull Worker Docker image
  community.docker.docker_image:
    name: "{{ worker_image }}"
    source: pull
- name: Ensure the /home/ubuntu/vote directory exists
  file:
   path: /home/ubuntu/worker
   state: directory
   owner: ubuntu
   group: ubuntu
   mode: '0755'

- name: Create and start Worker container
  docker_container:
    name: "{{ container_name }}"
    image: "{{ worker_image }}"
    state: started
    restart_policy: always
    volumes:
      - "/home/ubuntu/worker"
    command: "{{ worker_command }}"
    env:
      REDIS_HOST: "{{ redis_host }}"
      POSTGRES_HOST: "{{ postgres_host }}"
      POSTGRES_DB: "{{ postgres_db }}"
      POSTGRES_USER: "{{ postgres_user }}"
      POSTGRES_PASSWORD: "postgres"

- name: Wait for Redis
  ansible.builtin.wait_for:
    host: "{{ redis_host }}"
    port: 6379
    delay: 10
    timeout: 60

- name: Wait for Worker service
  ansible.builtin.wait_for:
    host: "{{ worker_host }}"
    port: 80
    delay: 10
    timeout: 60

- name: Success message
  debug:
    msg: "Worker service is running and processing votes."
