---
- name: Pull the Docker image
  community.docker.docker_image:
    name: mirmika/result
    source: pull
- name: Ensure the /home/ubuntu/vote directory exists
  file:
   path: /home/ubuntu/result
   state: directory
   owner: ubuntu
   group: ubuntu
   mode: '0755'
- name: Create and start the Docker container
  docker_container:
    name: result_app_container
    image: mirmika/result
    state: started
    restart_policy: always
    ports:
      - "80:80"
    volumes:
      - /ubuntu/home/result:/app
    command: "/bin/bash -c 'cd /app && npm ci && node server.js'"
    env:
      NODE_ENV: production

- name: Wait for the application to start
  ansible.builtin.wait_for:
    host: "{{ ansible_host }}"
    port: 80
    delay: 10
    timeout: 60
  when: server_process.rc == 0

- name: Display success message
  debug:
    msg: "The Result App is now running on http://localhost:80"
