---
- name: Kill process using port 81 (if it exists)
  ansible.builtin.shell: |
    pid=$(lsof -ti:81)
    if [ -n "$pid" ]; then
      kill -9 $pid
    fi

- name: Pull the Docker image
  community.docker.docker_image:
    name: mirmika/result
    source: pull

- name: Create and start the Docker container
  docker_container:
    name: result_app_container
    image: mirmika/result
    state: started
    restart_policy: always
    ports:
      - "81:80"
    env:
      NODE_ENV: production

- name: Wait for the application to start
  ansible.builtin.wait_for:
    host: "10.0.42.254"
    port: 81
    delay: 10
    timeout: 60

- name: Display success message
  debug:
    msg: "The Result App is now running on http://localhost:80"

