---
- name: Update apt packages (Ubuntu)
  apt:
    update_cache: 
  when: ansible_os_family == "Debian"

- name: Install Docker
  package:
    name: docker.io
    state: present
  when: ansible_os_family == "Debian"

- name: Ensure Docker service is running
  service:
    name: docker
    state: started
    enabled: yes

- name: Add user to Docker group
  user:
    name: ubuntu
    groups: docker
    append: yes 
