---
- name: Install Docker on EC2 instances
  hosts: frontend-result
  become: true
  tasks:
    - name: Update apt packages (Ubuntu)
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install Docker
      apt:
        name: docker.io
        state: present
      when: ansible_os_family == "Debian"

    - name: Ensure Docker service is running
      service:
        name: docker
        state: started
        enabled: yes

    - name: Add user to Docker group
      user:
        name: ubuntu
        groups: docker
        append: yes
---
- name: Pull Docker image, create container, install dependencies, and run the application
  hosts: frontend-result 
  become: yes 
  tasks:
    - name: Pull the Docker image
      community.docker.docker_image:
        name: mirmika/result  
        source: pull

    - name: Create and start the Docker container
      community.docker.docker_container:
        name: result_app_container  
        image: mirmika/result  
        state: started
        restart_policy: always  
        ports:
          - "80:80"  
        volumes:
          - /ubuntu/home/result:/app  # Mount the host directory to the container's app directory
        command: "/bin/bash -c 'cd /app && npm ci && node server.js'"  # Install dependencies and start the app
        environment:
          NODE_ENV: production  # Optional: Set environment variables for the app

    - name: Wait for the application to start
      ansible.builtin.wait_for:
        host: "{{ ansible_host }}"
        port: 80
        delay: 10
        timeout: 60
      when: server_process.rc == 0  # Wait for the application only if the previous task succeeded

    - name: Display success message
      debug:
        msg: "The Result App is now running on http://localhost:80"
